spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

#  spring.datasource.url=jdbc:postgresql://postgresql://postgres:GfIJtheQNZSgPQXoazmMBihZVlhOYMji@postgres.railway.internal:5432/railway
#  spring.datasource.username=postgres
#  spring.datasource.password=GfIJtheQNZSgPQXoazmMBihZVlhOYMji
#  spring.datasource.driver-class-name=org.postgresql.Driver
#  spring.jpa.hibernate.ddl-auto=update